version: '3'
services:
 mongo:
   image: mongo:5.0
   container_name: mongo
   restart: unless-stopped
   ports:
     - "27017:27017"
 mongo-express:
   image: mongo-express:0.54
   container_name: mexpress
   environment:
     - ME_CONFIG_MONGODB_ADMINUSERNAME=root
     - ME_CONFIG_MONGODB_ADMINPASSWORD=password
     - ME_CONFIG_MONGODB_URL=mongodb://root:password@mongo:27017/?authSource=admin
     - ME_CONFIG_BASICAUTH_USERNAME=mexpress
     - ME_CONFIG_BASICAUTH_PASSWORD=mexpress
   links:
     - mongo
   restart: unless-stopped
   ports:
     - "8081:8081"
 springapp:
   image: springapp:latest
   environment:
     MONGODB_URI: mongodb://mongo:27017/myDB
   ports:
     - 8082:8082
 python:
   image: flask-restapi:latest
   ports:
     - 5000:5000
 frontend:
   image: frontend:latest
   ports:
     - 4200:80